# Generated by Anaconda 37.4
# Generated by pykickstart v3.38
#version=DEVEL
# Use graphical install
text

reboot
skipx

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# System timezone
timezone America/New_York --utc

# Run the Setup Agent on first boot
firstboot --enable

