# Generated by Anaconda 37.4
# Generated by pykickstart v3.38
#version=DEVEL
# Use graphical install
text

rootpw --iscrypted somehash
#selinux --disabled
reboot
#firewall --disabled
skipx

# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# System timezone
timezone America/New_York --utc

# Run the Setup Agent on first boot
firstboot --enable

# Setup repos
repo --name=fedora --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-38&arch=$basearch
url --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-38&arch=$basearch



network --bootproto=dhcp --hostname=somehostname --activate

%pre --interpreter /bin/bash    
exec < /dev/tty6 > /dev/tty6 2> /dev/tty6    
chvt 6    
    
# Generated using Blivet version 3.4.3    
echo 'ignoredisk --only-use=nvme0n1' >> /tmp/part.ks    
# Partition clearing information    
echo 'clearpart --all --initlabel' >> /tmp/part.ks    
# Disk partitioning information    
echo 'part /boot/efi --fstype="efi" --size=512 --fsoptions="umask=0077,shortname=winnt"' >> /tmp/part.ks    
echo 'part /boot --fstype="ext4" --size=1024' >> /tmp/part.ks    
echo "part btrfs.249 --fstype=\"btrfs\" --ondisk=nvme0n1 --grow --encrypted --luks-version=luks2 --passphrase=somepassword" >> /tmp/part.ks
echo 'btrfs none --label=fedora btrfs.249' >> /tmp/part.ks
echo 'btrfs / --subvol --name=@root LABEL=fedora' >> /tmp/part.ks
echo 'btrfs /var --subvol --name=@var LABEL=fedora' >> /tmp/part.ks
echo 'btrfs /var/log --subvol --name=@var_log LABEL=fedora' >> /tmp/part.ks
echo 'btrfs /home --subvol --name=@home LABEL=fedora' >> /tmp/part.ks
chvt 1
exec < /dev/tty1 > /dev/tty1 2> /dev/tty1
%end

%include /tmp/part.ks
# Setup hostname
%pre --interpreter /bin/bash
exec < /dev/tty6 > /dev/tty6 2> /dev/tty6
chvt 6

echo "network --bootproto=dhcp --hostname=somehostname--activate" > /tmp/network.ks

chvt 1
exec < /dev/tty1 > /dev/tty1 2> /dev/tty1
%end
# Base Packages
%packages

# Exclude unwanted groups for minimal install
-@dial-up
-@input-methods
-@standard

# Install workstation-product-environment to resolve RhBug:1891500
@^workstation-product-environment

# Install cracklib-dicts and libpwquality for cryptsetup
cracklib
cracklib-dicts
libpwquality

# Install rpmfusion gpg keys
distribution-gpg-keys

# Exclude unwanted packages
-gfs2-utils
-reiserfs-utils
-cheese
-rhythmbox
-virtualbox-guest-additions
-gnome-software
%end

# Set root password
%post --interpreter /bin/bash
exec < /dev/tty6 > /dev/tty6 2> /dev/tty6
chvt 6

 read -p "Enter root password   : " rootpw

sleep 1

echo "$rootpw" | passwd --stdin root

chvt 1
exec < /dev/tty1 > /dev/tty1 2> /dev/tty1
%end

# Install SSH keys
%post --interpreter /bin/bash

echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
echo "Subsystem       sftp    /usr/libexec/openssh/sftp-server" >> /etc/ssh/sshd_config

systemctl enable sshd --now
%end

# Install SSH keys
%post --interpreter /bin/bash

#---- Install SSH key ----
mkdir -m0700 /root/.ssh/

cat <<EOF >/root/.ssh/authorized_keys
ssh-rsa AAAAB3.....eBqDhmMjjlc2qtPXfspFlMjpprEAPvO7GSYhsZ+255/yLF0SIf+z me@example.com
ssh-rsa AAAAB3.....eBqDhmMjjlc2qtPXfspFlMjpprEAPvO7GSYhsZ+255/yLF0SIf+z me2@example.com

EOF

### set permissions
chmod 0600 /root/.ssh/authorized_keys

### fix up selinux context
restorecon -R /root/.ssh/

%end
# Perform ansible-pull
%post --interpreter /bin/bash
exec < /dev/tty6 > /dev/tty6 2> /dev/tty6
chvt 6

# Install useful ansible galaxy packages
ansible-galaxy collection install community.general --force

LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ansible-pull -d /etc/local/ansible -C f-38-minimal-release -U https://github.com/Smurf/fedora-workstation.git

chvt 1
exec < /dev/tty1 > /dev/tty1 2> /dev/tty1
%end
# Set default boot target and remove gnome setup
%post --interpreter /bin/bash
exec < /dev/tty6 > /dev/tty6 2> /dev/tty6
chvt 6

dnf remove gnome-initial-setup -y
ln -sf /lib/systemd/system/runlevel5.target /etc/systemd/system/default.target

chvt 1
exec < /dev/tty1 > /dev/tty1 2> /dev/tty1
%end